#!/usr/bin/env python

from redminelib import Redmine
import app
import cli
import commands


# Load configuration
config = app.load_config()

# Authenticate
redmine = Redmine(config['url'], username=config['username'], password=config['password'])

# Get current user and determine yesterday's date
user = redmine.user.get('current')
activities = app.get_activities(redmine)

# Parse CLI arguments
parser = cli.arg_parser()
args = parser.parse_args(cli.preprocess_argv())
args = cli.validate_args(parser, args, config, activities)

# Execute command
app_data = {
    'user': user,
    'redmine': redmine,
    'activities': activities
}

command_function = getattr(commands, args.func)
command_function(args, config, app_data)
